package org.apache.james.mailboxmanager.torque.om.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Tue Sep 19 10:06:28 CEST 2006]
  *
  */
public class MessageFlagsMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.apache.james.mailboxmanager.torque.om.map.MessageFlagsMapBuilder";

    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("mailboxmanager");

        dbMap.addTable("message_flags");
        TableMap tMap = dbMap.getTable("message_flags");

        tMap.setPrimaryKeyMethod("none");


              tMap.addForeignPrimaryKey(
                "message_flags.MAILBOX_ID", new Long(0) , "message" ,
                "mailbox_id");
                    tMap.addForeignPrimaryKey(
                "message_flags.UID", new Long(0) , "message" ,
                "uid");
                          tMap.addColumn("message_flags.ANSWERED", new Integer(0) );
                                tMap.addColumn("message_flags.DELETED", new Integer(0) );
                                tMap.addColumn("message_flags.DRAFT", new Integer(0) );
                                tMap.addColumn("message_flags.FLAGGED", new Integer(0) );
                                tMap.addColumn("message_flags.RECENT", new Integer(0) );
                                tMap.addColumn("message_flags.SEEN", new Integer(0) );
                }
}
