package org.apache.james.mailboxmanager.torque.om;


/**
 * The skeleton for this class was autogenerated by Torque on:
 * 
 * [Wed Sep 06 11:15:19 CEST 2006]
 * 
 * You should add additional methods to this class to meet the application
 * requirements. This class will only be generated as long as it does not
 * already exist in the output directory.
 */
public class MessageRowPeer extends
        org.apache.james.mailboxmanager.torque.om.BaseMessageRowPeer {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1708650986440774692L;



}
