
package org.apache.james.mailboxmanager.torque.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Sep 05 21:34:06 CEST 2006]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class MessageHeader
    extends org.apache.james.mailboxmanager.torque.om.BaseMessageHeader
    implements Persistent
{

    /**
     * 
     */
    private static final long serialVersionUID = -9191792349506771474L;
}
