package org.apache.james.mailboxmanager.torque.om.map;

import java.util.Date;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Wed Sep 06 08:50:08 CEST 2006]
  *
  */
public class MessageMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.apache.james.mailboxmanager.torque.om.map.MessageMapBuilder";

    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("mailboxmanager");

        dbMap.addTable("message");
        TableMap tMap = dbMap.getTable("message");

        tMap.setPrimaryKeyMethod("none");


              tMap.addForeignPrimaryKey(
                "message.MAILBOX_ID", new Long(0) , "mailbox" ,
                "mailbox_id");
                    tMap.addPrimaryKey("message.UID", new Long(0) );
                          tMap.addColumn("message.FLAGS", new Integer(0) );
                                tMap.addColumn("message.INTERNAL_DATE", new Date() );
                }
}
