package org.apache.james.mailboxmanager.torque.om.map;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.ColumnMap;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Sun Dec 09 17:45:09 GMT 2007]
  *
  */
public class MessageFlagsMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "org.apache.james.mailboxmanager.torque.om.map.MessageFlagsMapBuilder";

    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public synchronized void doBuild() throws TorqueException
    {
        if ( isBuilt() ) {
            return;
        }
        dbMap = Torque.getDatabaseMap("mailboxmanager");

        dbMap.addTable("message_flags");
        TableMap tMap = dbMap.getTable("message_flags");
        tMap.setJavaName("MessageFlags");
        tMap.setOMClass( org.apache.james.mailboxmanager.torque.om.MessageFlags.class );
        tMap.setPeerClass( org.apache.james.mailboxmanager.torque.om.MessageFlagsPeer.class );
        tMap.setPrimaryKeyMethod("none");

        ColumnMap cMap = null;


    // ------------- Column: mailbox_id --------------------
        cMap = new ColumnMap( "mailbox_id", tMap);
        cMap.setType( new Long(0) );
        cMap.setTorqueType( "BIGINT" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(true);
        cMap.setNotNull(true);
        cMap.setJavaName( "MailboxId" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
            cMap.setDescription("Mailbox Id");
              cMap.setInheritance("false");
                  cMap.setForeignKey("message", "mailbox_id");
            cMap.setPosition(1);
          tMap.addColumn(cMap);
    // ------------- Column: uid --------------------
        cMap = new ColumnMap( "uid", tMap);
        cMap.setType( new Long(0) );
        cMap.setTorqueType( "BIGINT" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(true);
        cMap.setNotNull(true);
        cMap.setJavaName( "Uid" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
            cMap.setDescription("");
              cMap.setInheritance("false");
                  cMap.setForeignKey("message", "uid");
            cMap.setPosition(2);
          tMap.addColumn(cMap);
    // ------------- Column: answered --------------------
        cMap = new ColumnMap( "answered", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "BOOLEANINT" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "Answered" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
            cMap.setDescription("");
            cMap.setDefault("0");
            cMap.setInheritance("false");
                    cMap.setPosition(3);
          tMap.addColumn(cMap);
    // ------------- Column: deleted --------------------
        cMap = new ColumnMap( "deleted", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "BOOLEANINT" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "Deleted" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
            cMap.setDescription("");
            cMap.setDefault("0");
            cMap.setInheritance("false");
                    cMap.setPosition(4);
          tMap.addColumn(cMap);
    // ------------- Column: draft --------------------
        cMap = new ColumnMap( "draft", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "BOOLEANINT" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "Draft" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
            cMap.setDescription("");
            cMap.setDefault("0");
            cMap.setInheritance("false");
                    cMap.setPosition(5);
          tMap.addColumn(cMap);
    // ------------- Column: flagged --------------------
        cMap = new ColumnMap( "flagged", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "BOOLEANINT" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "Flagged" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
            cMap.setDescription("");
            cMap.setDefault("0");
            cMap.setInheritance("false");
                    cMap.setPosition(6);
          tMap.addColumn(cMap);
    // ------------- Column: recent --------------------
        cMap = new ColumnMap( "recent", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "BOOLEANINT" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "Recent" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
            cMap.setDescription("");
            cMap.setDefault("0");
            cMap.setInheritance("false");
                    cMap.setPosition(7);
          tMap.addColumn(cMap);
    // ------------- Column: seen --------------------
        cMap = new ColumnMap( "seen", tMap);
        cMap.setType( new Integer(0) );
        cMap.setTorqueType( "BOOLEANINT" );
        cMap.setUsePrimitive(true);
        cMap.setPrimaryKey(false);
        cMap.setNotNull(true);
        cMap.setJavaName( "Seen" );
        cMap.setAutoIncrement(false);
        cMap.setProtected(false);
            cMap.setDescription("");
            cMap.setDefault("0");
            cMap.setInheritance("false");
                    cMap.setPosition(8);
          tMap.addColumn(cMap);
        tMap.setUseInheritance(false);
    }
}
